name: Deploy

on:
  workflow_dispatch:
  push:
    paths: &paths
      - "website/**.[tj]sx?"
      - "website/**.css"
      - "website/**.astro"
      - "website/public/**"
      - "website/**.md"
      - "website/package.json"
      - "website/pnpm-lock.yaml"
      - "website/tsconfig.json"
      - ".github/workflows/deploy.yml"
    branches:
      - main
  pull_request:
    paths: *paths
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: website

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prod

      - name: Run build and check
        env:
          ASTRO_TELEMETRY_DISABLED: 1
        run: |
          pnpm run build

      - name: Set up npx cache
        uses: actions/cache@v4
        with:
          path: ~/.npm/_npx
          key: npx-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            npx-${{ runner.os }}

      - name: Deploy to CloudFlare Pages
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          npx wrangler@3 pages deploy ./dist --project-name=aleksac-me --branch ${{ github.head_ref || github.ref_name }}

      # This is needed by lighthouse ci to run on previews on branches other than
      # the default branch. This info needs to be obtained this way because actions
      # triggered by `worflow_run` run against the default branch
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
      - name: Save branch name
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          mkdir -p ./branch-name
          echo -n $BRANCH_NAME > ./branch-name/branch-name

      - uses: actions/upload-artifact@v4
        with:
          name: branch-name
          path: website/branch-name/
