name: Spellcheck

on:
  push:
    paths:
      - "**.md"
    branches:
      - main
  pull_request:
    paths:
      - "**.md"
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3
        with:
          extra_args: vale --all-files
